version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"

    schedule:
      interval: "monthly"

    # Bundle version updates and security updates each into a single PR.
    groups:
      python-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      python-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

    open-pull-requests-limit: 1
