GRADIENTS = {
    "nucleus_gradient": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.1},
    },
    "membrane_gradient": {
        "description": "gradient based on distance from the surface of the membrane mesh",
        "mode": "surface",
        "mode_settings": {"object": "membrane", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.01},
    },
    "apical_gradient": {
        "description": "gradient based on distance from a plane",
        "mode": "vector",
        "mode_settings": {"direction": [0, 0, 1], "center": "max"},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.7},
    },
    "struct_gradient": {
        "description": "gradient based on distance from the surface of the struct mesh",
        "mode": "surface",
        "mode_settings": {"object": "struct", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.01},
    },
    "struct_gradient_weak": {
        "description": "gradient based on distance from the surface of the struct mesh",
        "mode": "surface",
        "mode_settings": {"object": "struct", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.1},
    },
    "apical_gradient_0pt01": {
        "description": "gradient based on distance from a plane",
        "mode": "vector",
        "mode_settings": {"direction": [0, 0, 1], "center": "max"},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.01},
    },
    "apical_gradient_0pt1": {
        "description": "gradient based on distance from a plane",
        "mode": "vector",
        "mode_settings": {"direction": [0, 0, 1], "center": "max"},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.1},
    },
    "apical_gradient_0pt3": {
        "description": "gradient based on distance from a plane",
        "mode": "vector",
        "mode_settings": {"direction": [0, 0, 1], "center": "max"},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.3},
    },
    "apical_gradient_0pt5": {
        "description": "gradient based on distance from a plane",
        "mode": "vector",
        "mode_settings": {"direction": [0, 0, 1], "center": "max"},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.5},
    },
    "apical_gradient_0pt7": {
        "description": "gradient based on distance from a plane",
        "mode": "vector",
        "mode_settings": {"direction": [0, 0, 1], "center": "max"},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.7},
    },
    "apical_gradient_1": {
        "description": "gradient based on distance from a plane",
        "mode": "vector",
        "mode_settings": {"direction": [0, 0, 1], "center": "max"},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 1},
    },
    "apical_gradient_3": {
        "description": "gradient based on distance from a plane",
        "mode": "vector",
        "mode_settings": {"direction": [0, 0, 1], "center": "max"},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 3},
    },
    "apical_gradient_10": {
        "description": "gradient based on distance from a plane",
        "mode": "vector",
        "mode_settings": {"direction": [0, 0, 1], "center": "max"},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 10},
    },
    "apical_gradient_100": {
        "description": "gradient based on distance from a plane",
        "mode": "vector",
        "mode_settings": {"direction": [0, 0, 1], "center": "max"},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 100},
    },
    "nucleus_gradient_0pt01": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.01},
    },
    "nucleus_gradient_0pt03": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.03},
    },
    "nucleus_gradient_0pt05": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.05},
    },
    "nucleus_gradient_0pt07": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.07},
    },
    "nucleus_gradient_0pt1": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.1},
    },
    "nucleus_gradient_0pt3": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.3},
    },
    "nucleus_gradient_1": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 1},
    },
    "nucleus_gradient_10": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 10},
    },
    "nucleus_gradient_100": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 1},
    },
    "uniform": {
        "description": "uniform distribution throughout the cell volume",
        "mode": "uniform",
    },
}
