GRADIENTS = {
    "nucleus_gradient": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.1},
    },
    "membrane_gradient": {
        "description": "gradient based on distance from the surface of the membrane mesh",
        "mode": "surface",
        "mode_settings": {"object": "membrane", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.01},
    },
    "apical_gradient": {
        "description": "gradient based on distance from a plane",
        "mode": "vector",
        "mode_settings": {"direction": [0, 0, 1], "center": "max"},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.1},
    },
    "struct_gradient": {
        "description": "gradient based on distance from the surface of the struct mesh",
        "mode": "surface",
        "mode_settings": {"object": "struct", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.01},
    },
    "struct_gradient_weak": {
        "description": "gradient based on distance from the surface of the struct mesh",
        "mode": "surface",
        "mode_settings": {"object": "struct", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.1},
    },
    "nucleus_gradient_tuned": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.3},
    },
    "nucleus_gradient_0pt4": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.4},
    },
    "nucleus_gradient_0pt6": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.6},
    },
    "nucleus_gradient_0pt8": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 0.8},
    },
    "nucleus_gradient_1": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 1},
    },
    "nucleus_gradient_1pt2": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 1.2},
    },
    "nucleus_gradient_1pt4": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 1.4},
    },
    "nucleus_gradient_1pt6": {
        "description": "gradient based on distance from the surface of the nucleus mesh",
        "mode": "surface",
        "mode_settings": {"object": "nucleus", "scale_to_next_surface": False},
        "weight_mode": "exponential",
        "weight_mode_settings": {"decay_length": 1.6},
    },
}
